version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - app

  app:
    container_name: knote-app
    image: learnitguide/knotejs:1.0
    environment:
      MONGO_URL: mongodb://mongo_db_host:27017/dev
    ports:
      - "8082:3000"
    depends_on:
      - mongo
    links:
      - mongo:mongo_db_host

  mongo:
    container_name: knote-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
