version: "3.7"

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - ./nginx1/html:/usr/share/nginx/html

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx2/html:/usr/share/nginx/html
